### ISSUE TITLE
readme should include instructions on how to run generator

### ISSUE THREAD

**Issue by gavinking** [bjansen/ceylon-jooq-example#2]
@bjansen what are the commandline incantations to run the jOOQ generator?

This should be documented in the README.

**Comment by bjansen** [comment]
The procedure is described here: http://bjansen.github.io/ceylon/2015/08/24/ceylon-plus-jooq-equals-heart.html#generating-classes

I'll check this evening if it still works.

**Comment by gavinking** [comment]
@bjansen yeah but I would like to see that written in the README as actual commands I can just type in.

Also, we should add a link to that blog in the README.

**Comment by bjansen** [comment]
Right, I was implying that I would check the procedure, then add it to the README if it's still working :)

**Comment by gavinking** [comment]
OK good :)

**Comment by bjansen** [comment]
I added more info and a link to the blog post.

**Comment by gavinking** [comment]
Thanks!
